apiVersion: v1
kind: ResourceQuota
metadata:
  name: redis-cluster-quota
  namespace: redis-cluster
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "6"
    limits.memory: 12Gi
    requests.storage: 100Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "5"
